nelmio_cors:
  defaults:
  paths:
    api:
      #           allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_origin: [ 'http://localhost:5173' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
      max_age: 3600