nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(resolve:CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'POST']
    allow_headers: ['Content-Type', 'Authorization']
    allow_credentials: true
    max_age: 3600
  paths:
    '^/': ~